// Package hud implements the Agent HUD — an interactive dashboard for managing
// AI coding agents, MCP servers, workflows, memory, and the knowledge graph.
//
// The HUD runs as a local HTTP server that serves a Svelte frontend (embedded
// at build time) and exposes a JSON API backed by the loom daemon.
package hud

import (
	"context"
	"embed"
	"encoding/json"
	"log/slog"
	"net"
	"net/http"
	"net/http/pprof"
	"sync/atomic"
	"time"

	"go.opentelemetry.io/otel/trace"

	loomcache "github.com/crb2nu/loom/internal/cache"
	"github.com/crb2nu/loom/internal/hud/alerting"
	"github.com/crb2nu/loom/internal/hud/autofix"
	"github.com/crb2nu/loom/internal/hud/bridge"
	"github.com/crb2nu/loom/internal/hud/cfaccess"
	"github.com/crb2nu/loom/internal/hud/coordinator"
	"github.com/crb2nu/loom/internal/hud/domain"
	"github.com/crb2nu/loom/internal/hud/mirror"
	"github.com/crb2nu/loom/internal/hud/monitor"
	"github.com/crb2nu/loom/internal/hud/mrwatch"
	"github.com/crb2nu/loom/internal/hud/shuttle"
)

// frontendFS embeds the built Svelte HUD bundle. The bundle is generated by
// `make hud-frontend` (vite) and is NOT committed to git — committing the
// content-hashed dist caused a merge conflict on every concurrent HUD MR.
// CI (build:frontend job) and the Docker image (frontend builder stage) run
// vite before `go build`. The `all:` prefix and the committed
// frontend/dist/.gitkeep placeholder keep this embed valid even when vite has
// not run (e.g. a plain `go build`/`go test` on a fresh checkout), in which
// case the HUD serves a stub until the frontend is built.
//
//go:embed all:frontend/dist
var frontendFS embed.FS

// Config holds the configuration for the HUD server.
type Config struct {
	SocketPath   string // Path to the loom daemon Unix socket.
	RegistryPath string // Path to the MCP registry backing catalog-style HUD views.
	Dev          bool   // Development mode: enables CORS, skips embed.
	Port         int    // Port to listen on. 0 means pick a random available port.
	MetricsAddr  string // Daemon metrics/events HTTP address (e.g., "localhost:9090").
	Overlay      bool   // Enable macOS native overlay (NSPanel + Cmd+Shift+L hotkey).

	// Overlay appearance (only used when Overlay is true).
	OverlayEdge         string  // Screen edge: "right" or "left" (default "right").
	OverlayWidth        int     // Panel width in points (default 380).
	OverlayOpacity      float64 // Background opacity 0.0–1.0 (default 0.92).
	OverlayCornerRadius float64 // Corner radius in points (default 12).

	// Coordinator (FlexInfer LLM integration). Empty URL = disabled.
	// NOTE: FlexInferURL is misnamed for historical reasons — it actually
	// points at the LiteLLM gateway used by the coordinator/spawn paths,
	// not at the FlexInfer proxy that owns /v1/models. The aimodels
	// domain's flexinfer-models endpoint needs the proxy directly to
	// surface model availability badges; use FlexInferProxyURL for that
	// path. Renaming the historical field would touch many call sites
	// and break SOPS-encrypted secrets; the dual fields keep both
	// behaviors honest.
	FlexInferURL      string // LiteLLM gateway URL (litellm.ai.svc.cluster.local). Used by coordinator.
	FlexInferProxyURL string // FlexInfer proxy URL (pkg/flexinfer.DefaultProxyURL in-cluster). Used by aimodels/flexinfer-models endpoint.
	FlexInferKey      string // Optional API key for FlexInfer.
	CoordinatorModel  string // Default model for coordinator tasks (e.g., "gemma4-26b-a4b-gptq").

	// Webhook push: forward presence+session snapshots to a remote endpoint.
	WebhookURL     string // Push URL (e.g., "https://deck.flexinfer.ai/api/agents/hud/push").
	WebhookToken   string // Bearer token for push auth.
	WebhookResolve string // Override DNS resolution for webhook hostname (e.g., LAN IP to bypass Cloudflare).
	AdminToken     string // Token required for admin-only HUD mutations.

	// Cloudflare Access SSO → HUD admin. When a user reaches the HUD through
	// Cloudflare Access (Google/Gmail login), Cloudflare injects a signed
	// Cf-Access-Jwt-Assertion header; if it verifies and the email is in
	// CFAccessAdminEmails, the request is treated as admin without a token.
	// Disabled unless CFAccessTeamDomain and CFAccessAdminEmails are both set;
	// the AdminToken path stays as the LAN/CLI fallback. See internal/hud/cfaccess.
	CFAccessTeamDomain  string // e.g. "flexinfer.cloudflareaccess.com" ($HUD_CF_ACCESS_TEAM_DOMAIN).
	CFAccessAUD         string // Access application AUD tag; "" skips the aud check ($HUD_CF_ACCESS_AUD).
	CFAccessAdminEmails string // Comma-separated admin email allowlist ($HUD_ADMIN_EMAILS).

	// AdminTrustedCIDRs grants admin (no token) to requests whose real client
	// IP falls in one of these CIDRs — the LAN trusted-network path for when the
	// HUD is reached directly through the internal ingress (split-horizon DNS),
	// bypassing Cloudflare. Comma-separated ($HUD_ADMIN_TRUSTED_CIDRS); empty =
	// off. Set to the LAN subnet only (never the pod/service CIDRs). See
	// internal/hud/trusted_network.go for the trust model.
	AdminTrustedCIDRs string

	// Mobile operator API auth policy.
	MobileOperatorToken  string // Bearer token for /api/mobile/v1 routes.
	MobileOperatorScopes string // Comma-separated scopes granted to mobile token.

	// Mobile rate limiting.
	MobileRateLimitMutation int // Max mutation requests per actor per minute (0 = disabled).
	MobileRateLimitRead     int // Max read requests per actor per minute (0 = disabled).

	// Mobile push notifications (behind feature flag).
	MobilePushEnabled bool // Enable push notification endpoints (default: false).

	// APNs configuration for push delivery.
	APNsKeyPath string // Path to .p8 signing key.
	APNsKeyID   string // APNs key ID from Apple Developer portal.
	APNsTeamID  string // Apple Developer Team ID.
	APNsTopic   string // APNs topic (bundle ID).
	APNsSandbox bool   // Use sandbox APNs endpoint (development).

	// TLS for gateway mode.
	TLSCert     string // Path to PEM certificate file.
	TLSKey      string // Path to PEM private key file.
	BindAddress string // Listen address (default: 127.0.0.1).

	// TUI mode: launch a bubbletea terminal UI instead of the web dashboard.
	TUI bool

	// Spawn orchestrator (headless agent spawning via devbox K8s backend).
	SpawnEnabled                      bool    // Enable spawn endpoints (default: false).
	SpawnControllerID                 string  // Stable logical owner for shared spawn-state recovery.
	SpawnRecoveryAuthority            bool    // Claim legacy shared rows and rowless orphan pods.
	SpawnKubeconfig                   string  // Kubeconfig for spawn K8s backend.
	SpawnNamespace                    string  // K8s namespace for spawn pods (default: "devbox").
	SpawnRegistry                     string  // Image registry (default: "registry.harbor.lan").
	SpawnSyncMode                     string  // Workspace sync: "git-clone" or "nfs".
	SpawnGitBaseURL                   string  // Git base URL for git-clone mode.
	SpawnGitSecret                    string  // K8s secret with git token.
	SpawnGitCloneImage                string  // git image for git-clone init containers.
	SpawnProjects                     string  // Comma-separated project names for spawn picker.
	SpawnDefaultCPU                   float64 // Default CPU limit for spawned agent pods.
	SpawnDefaultMemory                int     // Default memory limit for spawned agent pods in MB.
	SpawnMaxConcurrent                int     // Maximum active spawned agents.
	SpawnMaxConcurrentBuilds          int     // Maximum concurrent spawn image builds.
	SpawnBuildCPURequest              string  // Buildah pod CPU request for spawn images.
	SpawnBuildCPULimit                string  // Buildah pod CPU limit for spawn images.
	SpawnBuildMemoryRequest           string  // Buildah pod memory request for spawn images.
	SpawnBuildMemoryLimit             string  // Buildah pod memory limit for spawn images.
	SpawnBuildEphemeralStorageRequest string  // Buildah pod ephemeral-storage request for spawn images.
	SpawnBuildEphemeralStorageLimit   string  // Buildah pod ephemeral-storage limit for spawn images.
	SpawnBuildAvoidNodes              string  // Comma-separated node names to avoid for spawn image builds.

	// Harvester KubeVirt VM substrate (Mills harvester-vm backend).
	// When SpawnHarvesterKubeconfig is empty, the harvester-vm backend
	// is NOT registered and any spawn request with Substrate="harvester-vm"
	// falls back to the default (k8s) backend with a warning log.
	// Spec: .loom/45-product-spec-mills-harvester-vm-substrate-2026-05-25.md
	SpawnHarvesterKubeconfig       string // Kubeconfig for the Harvester cluster.
	SpawnHarvesterBaseImage        string // VirtualMachineImage name (e.g. "mills-devbox-base-2026-05-25").
	SpawnHarvesterNamespace        string // VM namespace (default: "default" — Slice 1.5 same-NS PVC pattern).
	SpawnHarvesterStorageClass     string // Storage class for per-VM PVCs (e.g. "longhorn-image-<id>"). Required when SpawnHarvesterKubeconfig set.
	SpawnHarvesterNetworkAttachDef string // Multus NAD ref (default: "default/lan10g").
	SpawnHarvesterDefaultVCPUs     int    // Per-VM vCPU count (default: 2).
	SpawnHarvesterDefaultMemMi     int    // Per-VM memory MiB (default: 4096).
	SpawnHarvesterDefaultDiskGi    int    // Per-VM OS disk GiB (default: 20).
	SpawnHarvesterSSHUser          string // Cloud-init-provisioned user (default: "agent").

	// Pipeline monitoring (GitLab CI).
	PipelineProjects string // Comma-separated GitLab project paths to monitor.

	// Inbound webhook event bridge (CI → agent dispatch).
	WebhookInboundEnabled bool   // Enable inbound webhook endpoints (default: false).
	WebhookGitLabSecret   string // X-Gitlab-Token secret for verifying GitLab webhooks.
	WebhookGitHubSecret   string // HMAC secret for verifying GitHub X-Hub-Signature-256.

	// Auto-fix engine (LLM pipeline-failure diagnosis + fix orchestration).
	// Default off until soak, mirroring the overseers pattern: the alerting
	// domain's /api/autofix/* routes stay registered and serve honest empty
	// lists / 503s on mutations while disabled.
	AutofixEnabled bool // Enable the autofix engine (default: false).

	// Loom Mills operator (cluster-side autonomy loop). When unset the
	// HUD's /api/mills/* proxy returns 503 and the Mills view shows an
	// empty-state instead of crashing.
	MillsOperatorURL   string // base URL, e.g. http://loom-mills-operator.loom-mills.svc.cluster.local:8090
	MillsOperatorToken string // admin bearer for mutation routes (LOOM_MILLS_ADMIN_TOKEN on the operator)

	// EmbedSubset selects which views the HUD exposes when running as an
	// embedded surface (e.g., inside an iframe in another product). Values:
	//
	//   "" / "full"   — default; every panel is registered and routable.
	//   "operator"    — Overview + Operations/Fleet + Activity/Stream only;
	//                   all other top-level views are hidden in the nav and
	//                   navigating to a hidden route falls back to Overview.
	//                   Non-allowlisted JSON API routes are skipped at
	//                   handler registration time as a defense-in-depth
	//                   measure for iframe embeds.
	//
	// See .loom/117 Slice B5 for the rationale.
	EmbedSubset string
}

// App is the HUD application. It holds the daemon client, agent bridge,
// background monitors, and an in-memory cache used to reduce repeated calls
// to the daemon.
type App struct {
	config       Config
	client       bridge.Caller
	agent        *bridge.AgentBridge
	cache        loomcache.Store
	cacheBackend string // "memory" or "redis" — exposed in /api/health.
	logger       *slog.Logger

	// runtimeAdminToken is a hot-reloadable override for config.AdminToken
	// populated by SIGHUP-driven env-file reload (see daemon.Reload).
	// When non-nil it takes precedence over the static config field; when
	// nil, AdminToken() falls back to config.AdminToken so initial
	// startup and tests that mutate config.AdminToken directly keep working.
	runtimeAdminToken atomic.Pointer[string]

	// accessVerifier verifies Cloudflare Access SSO JWTs to grant admin without
	// a token. Nil when the feature is disabled (a nil *Verifier is safe — its
	// AdminEmail always reports "not admin"). See internal/hud/cfaccess.
	accessVerifier *cfaccess.Verifier

	// adminTrustedNets is the parsed HUD_ADMIN_TRUSTED_CIDRS allowlist — a
	// client IP in one of these is granted admin without a token (the LAN
	// trusted-network path). Empty = off. See internal/hud/trusted_network.go.
	adminTrustedNets []*net.IPNet

	// Background monitors — poll the bridge and maintain cached snapshots.
	fleetMonitor         *monitor.FleetMonitor
	healthMonitor        *monitor.HealthMonitor
	memoryMonitor        *monitor.MemoryMonitor
	workflowMonitor      *monitor.WorkflowMonitor
	streamMonitor        *monitor.StreamMonitor
	sandboxMonitor       *monitor.SandboxMonitor
	costMonitor          *monitor.CostMonitor
	pipelineMonitor      *monitor.PipelineMonitor
	contextHealthMonitor *monitor.ContextHealthMonitor
	codebaseMonitor      *monitor.CodebaseMonitor
	shuttleMonitor       *shuttle.ShuttleMonitor
	otelMonitor          *monitor.OTelMonitor
	millsMonitor         *monitor.MillsMonitor

	// mrwatchPoller maintains the branch→MR status registry. Nil when GitLab
	// is not configured (GITLAB_API_URL/GITLAB_TOKEN unset); a nil poller
	// still serves an empty snapshot so the /api/mrwatch routes never 500.
	mrwatchPoller *mrwatch.Poller

	// mrwatchShepherd takes bounded auto-actions on unhealthy MRs after each
	// poll (M4). Nil when GitLab is unconfigured; disabled by default even when
	// present (LOOM_MRWATCH_SHEPHERD must be set truthy to enable actions).
	// Actions() is nil-safe so /api/mrwatch/actions works regardless.
	mrwatchShepherd *mrwatch.Shepherd

	// mrwatchNotifier raises durable inbox nudges + attention-lane items on MR
	// transitions into unhealthy states (M5). Nil when GitLab is unconfigured;
	// enabled by default when present (LOOM_MRWATCH_NOTIFY gates it). Attention()
	// is nil-safe so the mobile dashboard renders regardless.
	mrwatchNotifier *mrwatch.Notifier

	// hudMirror federates this daemon's active presence to a remote HUD
	// when LOOM_HUD_MIRROR_URL is set. Nil when mirroring is disabled.
	hudMirror *mirror.Service

	// Shuttle engine — auto-dispatch, load balancing, conflict prevention.
	shuttleEngine *shuttle.Engine

	// Alert engine — pipeline failure alerting and notification dispatch.
	alertEngine   *alerting.AlertEngine
	autofixEngine *autofix.AutoFixEngine

	// SSE streaming — daemon events → browser clients.
	sseHub *SSEHub

	// Coordinator — optional LLM-powered agent context intelligence.
	coordinator         *coordinator.Coordinator
	coordinatorMetrics  *coordinator.Metrics
	agentContextMetrics *AgentContextMetrics
	agentContextLatest  *AgentContextLatestStore

	// Timeline event log — ring buffer for unified activity timeline.
	eventLog *EventLog

	// blocked tracks sessions currently waiting on a human, folded from the
	// flightdeck bridge's agent.blocked / agent.unblocked events. Drives the
	// fleet dashboard's "N blocked" badge.
	blocked *blockedStore

	// Nudge queue — pending nudges per agent, delivered via heartbeat response.
	nudgeQueue *NudgeQueue

	// Mobile API hardening.
	mobileRateLimiter    *MobileRateLimiter
	mobileRevocationList *MobileTokenRevocationList
	deviceTokenStore     *DeviceTokenStore // Push notification device tokens (MBL-7).

	// OTel instrumentation.
	tracer       trace.Tracer
	metrics      *HUDMetrics
	otelShutdown func(context.Context) error

	// Push notification bridge (SSE events → APNs).
	pushBridge *PushEventBridge

	// Headless agent spawn orchestrator.
	spawner                  *SpawnOrchestrator
	spawnControllerOwnerLock *spawnControllerOwnerLock

	// Domain registry — self-contained feature modules that own their routes.
	domainRegistry *domain.Registry
}

const (
	// pushTokenCleanupInterval controls how often stale push tokens are pruned.
	pushTokenCleanupInterval = 1 * time.Hour
	// pushTokenMaxIdle controls token staleness before automatic removal.
	pushTokenMaxIdle = 30 * 24 * time.Hour
)

// SpawnOrchestrator returns the App's concrete spawn orchestrator, or
// nil if spawning is disabled in this deployment. Exposed so the daemon
// layer can wire the orchestrator into the weaver SpawnBridge.
//
// Distinct from Spawner() (which returns a mobile.SpawnerOps adapter for
// the mobile REST handlers) — this returns the raw *SpawnOrchestrator
// so callers can reach Spawn/Wait/GetSpawn without the mobile facade.
func (a *App) SpawnOrchestrator() *SpawnOrchestrator {
	return a.spawner
}

// AdminToken returns the currently-effective admin token. When SIGHUP-
// driven env reload has installed a runtime override, that value wins;
// otherwise the static value passed at NewApp time via config.AdminToken
// is returned. Callers should use this in preference to a.config.AdminToken
// directly so hot-reload works.
func (a *App) AdminToken() string {
	if p := a.runtimeAdminToken.Load(); p != nil {
		return *p
	}
	return a.config.AdminToken
}

// SetAdminToken installs a runtime admin-token override visible to
// every subsequent AdminToken() read. An empty string clears the
// override (falls back to config.AdminToken).
func (a *App) SetAdminToken(token string) {
	if token == "" {
		a.runtimeAdminToken.Store(nil)
		return
	}
	a.runtimeAdminToken.Store(&token)
}

// writeJSON marshals v as JSON and writes it to the response.
func (a *App) writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(v); err != nil {
		a.logger.Error("failed to write JSON response", "error", err)
	}
}

// writeError writes a JSON error response.
func (a *App) writeError(w http.ResponseWriter, status int, message string, err error) {
	if err != nil {
		a.logger.Error(message, "error", err)
	}
	a.writeJSON(w, status, map[string]string{"error": message})
}

// pprof handler wrappers for custom ServeMux registration.
func pprofIndex(w http.ResponseWriter, r *http.Request)   { pprof.Index(w, r) }
func pprofCmdline(w http.ResponseWriter, r *http.Request) { pprof.Cmdline(w, r) }
func pprofProfile(w http.ResponseWriter, r *http.Request) { pprof.Profile(w, r) }
func pprofSymbol(w http.ResponseWriter, r *http.Request)  { pprof.Symbol(w, r) }
func pprofTrace(w http.ResponseWriter, r *http.Request)   { pprof.Trace(w, r) }
