<script lang="ts">
  import { millsStore,type BoltCard,type BoltGrade,type BoltsResponse } from '../../stores/mills.svelte.ts';
  import { focusTrap } from '../../actions/focusTrap'; import { formatChange,formatScore } from '../../utils/shiftHelpers.ts'; import { fmtCost } from './shared/format.ts';
  let {onclose}:{onclose:()=>void}=$props(); let loading=$state(true); let archive=$state<BoltsResponse|null>(null); let grading=$state<Record<string,boolean>>({}); let notes=$state<Record<string,string>>({});
  $effect(()=>{let live=true;millsStore.fetchBolts('7d').then(r=>{if(live){archive=r;loading=false}});return()=>{live=false}}); function key(c:BoltCard){return c.run_id??c.backlog_id}
  async function grade(c:BoltCard,value:BoltGrade){const id=key(c);if(grading[id])return;grading={...grading,[id]:true};try{await millsStore.gradeBolt(c,value,notes[id]??c.grade?.note??'');if(archive)archive={...archive,bolts:archive.bolts.map(x=>key(x)===id?{...x,grade:{value,note:notes[id]??'',actor:'hud',at:new Date().toISOString()}}:x)}}finally{grading={...grading,[id]:false}}}
</script>
<svelte:window onkeydown={(e)=>{if(e.key==='Escape')onclose()}}/><button class="scrim" onclick={onclose} aria-label="Close bolt archive"></button><div class="modal" role="dialog" aria-modal="true" aria-label="Bolt archive" use:focusTrap><header><div><strong>Bolt archive</strong><small>the week's server-composed cards</small></div><button onclick={onclose}>✕</button></header>{#if loading}<p class="status">unrolling the take-up beam…</p>{:else if !archive}<p class="status">No bolt archive available.</p>{:else if !archive.bolts.length}<p class="status">No bolts in this window.</p>{:else}<main>{#each archive.bolts as card (key(card))}<article class="card"><h3>{card.title||card.backlog_id}</h3><div class="meta"><span>{card.backlog_id}</span>{#if card.mr.iid}<a href={card.mr.url} target="_blank" rel="noopener noreferrer">!{card.mr.iid}</a>{/if}<span>{formatChange(card.diff.files,card.diff.added,card.diff.removed)}</span><span>eval {formatScore(card.eval.min_score)}</span><span>{fmtCost(card.cost_usd)}</span>{#if card.escalation}<span>{card.escalation.class} · {card.escalation.signature} · {card.escalation.week_occurrences} this week</span>{/if}</div>{#if card.grade}<p>{card.grade.value}{#if card.grade.note}{' — '}{card.grade.note}{/if}</p>{/if}<div class="grade">{#each ['keep','meh','regret'] as value}<button aria-pressed={card.grade?.value===value} disabled={grading[key(card)]} onclick={()=>grade(card,value as BoltGrade)}>{value}</button>{/each}<input aria-label={`Grade note for ${card.backlog_id}`} value={notes[key(card)]??card.grade?.note??''} oninput={(e)=>notes={...notes,[key(card)]:e.currentTarget.value}}/></div></article>{/each}</main><footer>{archive.bolts.length} cards this week</footer>{/if}</div>
<style>.scrim{position:fixed;inset:0;background:#0008;border:0;z-index:var(--z-modal)}.modal{position:fixed;inset:7% max(3%,calc((100% - 760px)/2));z-index:calc(var(--z-modal) + 1);background:var(--bg-secondary);border:1px solid var(--border);border-radius:var(--radius-lg);overflow:auto;padding:var(--space-4)}header,header div,.meta,.grade{display:flex;gap:var(--space-2);align-items:center;flex-wrap:wrap}header{justify-content:space-between;border-bottom:1px solid var(--border);padding-bottom:var(--space-3)}header div{flex-direction:column;align-items:flex-start}.status{padding:var(--space-6)}.card{border:1px solid var(--border);border-radius:var(--radius-md);padding:var(--space-3);margin:var(--space-2) 0}.meta{font-size:var(--text-xs);color:var(--fg-muted)}.grade{margin-top:var(--space-2)}footer{padding-top:var(--space-3);color:var(--fg-muted)}</style>
