import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { flushSync, mount, unmount } from 'svelte';
import GradeWalkthrough from './GradeWalkthrough.svelte';
import { millsStore, type BoltCard } from '../../stores/mills.svelte.ts';

const card = (id: string): BoltCard => ({ run_id:id,backlog_id:`bl-${id}`,title:`Title ${id}`,spec_headline:'',outcome:'merged',merged_at:null,mr:{iid:12,url:'https://gitlab.test/12'},diff:{files:2,added:8,removed:3,source:'artifacts'},eval:{min_score:.8,verdicts:[]},gates_failed:[],attempts:1,cost_usd:1.25,template:'implement',escalation:null,grade:null });
let target:HTMLElement; let component:Record<string,unknown>|null;
beforeEach(()=>{target=document.createElement('div');document.body.appendChild(target)}); afterEach(()=>{if(component)void unmount(component);component=null;target.remove();vi.restoreAllMocks()});
describe('GradeWalkthrough',()=>{
  it('steps next/previous and grades the original queue from 1/2/3',async()=>{const grade=vi.spyOn(millsStore,'gradeBolt').mockResolvedValue(null);let cards=[card('1'),card('2'),card('3')];const ongraded=vi.fn((graded: BoltCard)=>{cards=cards.filter(candidate=>candidate.run_id!==graded.run_id)});component=mount(GradeWalkthrough,{target,props:{cards,onclose:vi.fn(),ongraded}}) as Record<string,unknown>;flushSync();expect(target.textContent).toContain('1 of 3');(target.querySelectorAll('footer button')[1] as HTMLButtonElement).click();flushSync();expect(target.textContent).toContain('2 of 3');(target.querySelectorAll('footer button')[0] as HTMLButtonElement).click();flushSync();window.dispatchEvent(new KeyboardEvent('keydown',{key:'1'}));await vi.waitFor(()=>expect(grade).toHaveBeenCalledWith(expect.objectContaining({run_id:'1'}),'keep',''));await vi.waitFor(()=>expect(target.textContent).toContain('2 of 3'));window.dispatchEvent(new KeyboardEvent('keydown',{key:'2'}));await vi.waitFor(()=>expect(grade).toHaveBeenCalledWith(expect.objectContaining({run_id:'2'}),'meh',''));await vi.waitFor(()=>expect(target.textContent).toContain('3 of 3'));window.dispatchEvent(new KeyboardEvent('keydown',{key:'3'}));await vi.waitFor(()=>expect(grade).toHaveBeenCalledWith(expect.objectContaining({run_id:'3'}),'regret',''));expect(grade.mock.calls.map(([graded])=>graded.run_id)).toEqual(['1','2','3'])});
  it('ignores grade keys from an input',()=>{const grade=vi.spyOn(millsStore,'gradeBolt');component=mount(GradeWalkthrough,{target,props:{cards:[card('1')],onclose:vi.fn()}}) as Record<string,unknown>;const input=document.createElement('input');target.appendChild(input);input.dispatchEvent(new KeyboardEvent('keydown',{key:'1',bubbles:true}));expect(grade).not.toHaveBeenCalled()});
});
