<script lang="ts">
  import { millsStore,type BoltCard,type BoltGrade,type ShiftReportResponse } from '../../stores/mills.svelte.ts';
  import { focusTrap } from '../../actions/focusTrap'; import { formatChange,formatCoverage,formatScore } from '../../utils/shiftHelpers.ts'; import { fmtCost } from './shared/format.ts'; import GradeWalkthrough from './GradeWalkthrough.svelte';
  let {onclose=()=>{},embedded=false}:{onclose?:()=>void;embedded?:boolean}=$props(); let loading=$state(true); let report=$state<ShiftReportResponse|null>(null); let copied=$state(false); let walkthrough=$state(false); let walkthroughCards=$state<BoltCard[]>([]); let grading=$state<Record<string,boolean>>({}); let notes=$state<Record<string,string>>({}); let ungraded=$derived(report?.bolts.filter(c=>!c.grade)??[]);
  $effect(()=>{let live=true;millsStore.fetchShiftReport('24h').then(r=>{if(live){report=r;loading=false}});return()=>{live=false}});
  function key(c:BoltCard){return c.run_id??c.backlog_id} async function grade(c:BoltCard,value:BoltGrade){const id=key(c);if(grading[id])return;grading={...grading,[id]:true};try{await millsStore.gradeBolt(c,value,notes[id]??c.grade?.note??'');if(report)report={...report,bolts:report.bolts.map(x=>key(x)===id?{...x,grade:{value,note:notes[id]??'',actor:'hud',at:new Date().toISOString()}}:x)}}finally{grading={...grading,[id]:false}}}
  async function copyMarkdown(){if(report){await navigator.clipboard.writeText(report.markdown);copied=true}} function downloadMarkdown(){if(!report)return;const u=URL.createObjectURL(new Blob([report.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='shift-report.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)} function openWalkthrough(){walkthroughCards=[...ungraded];walkthrough=true} function walked(c:BoltCard,value:BoltGrade){if(report)report={...report,bolts:report.bolts.map(x=>key(x)===key(c)?{...x,grade:{value,note:'',actor:'hud',at:new Date().toISOString()}}:x)}}
  function trapWhenModal(node:HTMLElement){if(!embedded)return focusTrap(node)}
</script>
<svelte:window onkeydown={(e)=>{if(!embedded&&e.key==='Escape'&&!walkthrough)onclose()}}/>{#if !embedded}<button class="scrim" onclick={onclose} aria-label="Close shift report"></button>{/if}<div class="modal" class:embedded role={embedded?'region':'dialog'} aria-modal={embedded?undefined:'true'} aria-label="Shift report" use:trapWhenModal><header><div><strong>Shift report</strong><small>server-composed shift ledger</small></div><nav><button onclick={copyMarkdown} disabled={!report}>{copied?'✓ copied':'⧉ copy md'}</button><button onclick={downloadMarkdown} disabled={!report}>↓ .md</button>{#if !embedded}<button onclick={onclose} aria-label="Close shift report">✕</button>{/if}</nav></header>
{#if loading}<p class="status">tallying the shift…</p>{:else if !report}<p class="status">No shift report available.</p>{:else}<main><section class="narrative">{#each report.narrative_lines as line}<p>{line}</p>{/each}</section><section aria-label="Bolts"><h2>bolts</h2>{#each report.bolts as card (key(card))}{@render Card(card)}{/each}</section>{#if report.sparks.length}<section aria-label="Sparks"><h2>sparks</h2>{#each report.sparks as card (key(card))}{@render Card(card,true)}{/each}</section>{/if}<section class="kpis" aria-label="KPI delta"><h2>KPI delta</h2>{#each Object.entries(report.kpi_delta) as [name,m]}<span>{name.replaceAll('_',' ')}: {m.now} (was {m.prev})</span>{/each}</section><section class="taste" aria-label="Taste coverage"><h2>taste</h2><span>{report.taste.graded_this_shift}/{report.taste.bolts_this_shift} graded</span><span>14d coverage {formatCoverage(report.taste.coverage_14d)}</span>{#if report.taste.coverage_gate!=null}<span>gate {formatCoverage(report.taste.coverage_gate)}</span>{/if}<span>{report.taste.ranker_armed?'ranker armed':'ranker disarmed'}</span>{#if ungraded.length}<button onclick={openWalkthrough}>grade the shift: {ungraded.length} cards</button>{/if}</section></main>{/if}</div>{#if walkthrough}<GradeWalkthrough cards={walkthroughCards} onclose={()=>walkthrough=false} ongraded={walked}/>{/if}
{#snippet Card(card:BoltCard,spark=false)}<article class="card" class:spark><h3>{card.title||card.backlog_id}</h3><div class="meta"><span>{card.backlog_id}</span>{#if card.mr.iid}<a href={card.mr.url} target="_blank" rel="noopener noreferrer">!{card.mr.iid}</a>{/if}<span>{formatChange(card.diff.files,card.diff.added,card.diff.removed)}</span><span>eval {formatScore(card.eval.min_score)}</span><span>{fmtCost(card.cost_usd)}</span>{#if card.escalation}<span>{card.escalation.class} · {card.escalation.signature} · {card.escalation.week_occurrences} this week</span>{/if}</div>{#if card.grade}<p class="head-grade">{card.grade.value}{#if card.grade.note}{' — '}{card.grade.note}{/if}</p>{/if}<div class="grade">{#each ['keep','meh','regret'] as value}<button aria-pressed={card.grade?.value===value} disabled={grading[key(card)]} onclick={()=>grade(card,value as BoltGrade)}>{value}</button>{/each}<input aria-label={`Grade note for ${card.backlog_id}`} value={notes[key(card)]??card.grade?.note??''} oninput={(e)=>notes={...notes,[key(card)]:e.currentTarget.value}}/></div></article>{/snippet}
<style>.scrim{position:fixed;inset:0;background:#0008;border:0;z-index:var(--z-modal)}.modal{position:fixed;inset:6% max(3%,calc((100% - 760px)/2));z-index:calc(var(--z-modal) + 1);background:var(--bg-secondary);border:1px solid var(--border);border-radius:var(--radius-lg);overflow:auto;padding:var(--space-4)}.modal.embedded{position:static;inset:auto;z-index:auto;overflow:visible}header,header div,nav,.meta,.grade,.kpis,.taste{display:flex;gap:var(--space-2);align-items:center;flex-wrap:wrap}header{justify-content:space-between;border-bottom:1px solid var(--border);padding-bottom:var(--space-3)}header div{flex-direction:column;align-items:flex-start}.status{padding:var(--space-6)}.card{border:1px solid var(--border);border-radius:var(--radius-md);padding:var(--space-3);margin:var(--space-2) 0}.card.spark{border-color:var(--warning)}h2{font-size:var(--text-sm);text-transform:uppercase}.meta{font-size:var(--text-xs);color:var(--fg-muted)}.head-grade{font-size:var(--text-xs)}.grade{margin-top:var(--space-2)}.taste,.kpis{margin-top:var(--space-4);padding:var(--space-3);background:var(--bg-primary);border-radius:var(--radius-md)}</style>
