package clients

import (
	"context"
	"strings"
	"testing"

	"github.com/crb2nu/loom/pkg/mills/council"
	"github.com/crb2nu/loom/pkg/mills/eval"
)

func TestFlexInferCouncilReviewer(t *testing.T) {
	cli := newStubClient(t, `{
		"model":"qwen3-8b",
		"choices":[{"message":{"role":"assistant","content":"# Security\n\nScope is tight."}}],
		"usage":{"prompt_tokens":100,"completion_tokens":20,"total_tokens":120}
	}`, 200)
	reviewer := &FlexInferCouncilReviewer{Client: cli}

	out, err := reviewer.Review(context.Background(), &council.Brief{Markdown: "Ship Mills."}, council.ReviewerLens{
		Name: "security", Model: "qwen3-8b", Backend: "flexinfer",
	})
	if err != nil {
		t.Fatalf("Review: %v", err)
	}
	if out.Lens.Name != "security" || !strings.Contains(out.Markdown, "Scope is tight") {
		t.Fatalf("unexpected review output: %+v", out)
	}
	if out.CostUSD <= 0 {
		t.Fatalf("CostUSD = %v, want positive estimate", out.CostUSD)
	}
}

func TestFlexInferCouncilEditorSplitsArtifacts(t *testing.T) {
	cli := newStubClient(t, `{
		"model":"qwen3-8b",
		"choices":[{"message":{"role":"assistant","content":"## Research\nR\n\n## Product Spec\nP\n\n## Implementation Plan\nI"}}],
		"usage":{"prompt_tokens":100,"completion_tokens":50,"total_tokens":150}
	}`, 200)
	editor := &FlexInferCouncilEditor{Client: cli, Model: "qwen3-8b"}

	out, err := editor.Edit(context.Background(), &council.Brief{Markdown: "Brief"}, []council.ReviewerOutput{
		{Lens: council.ReviewerLens{Name: "architecture", Model: "qwen3-8b", Backend: "flexinfer"}, CostUSD: 0.02},
	})
	if err != nil {
		t.Fatalf("Edit: %v", err)
	}
	if len(out.Documents) != 3 {
		t.Fatalf("documents = %d, want 3", len(out.Documents))
	}
	if out.Documents[0].Body != "R" || out.Documents[1].Body != "P" || out.Documents[2].Body != "I" {
		t.Fatalf("documents not split correctly: %+v", out.Documents)
	}
	if out.Sidecar.CostUSD.Local <= 0.02 {
		t.Fatalf("local cost = %v, want editor + review cost", out.Sidecar.CostUSD.Local)
	}
	if out.Sidecar.Notes != "generated by FlexInfer-backed council participants" {
		t.Fatalf("notes = %q", out.Sidecar.Notes)
	}
}

// Regression: a model that returns an empty (or whitespace-only) string
// must surface as EditorOutput.Empty=true so the runner can demote the
// council run's outcome to error instead of silently writing a placeholder
// and marking the run success.
func TestFlexInferCouncilEditorMarksEmptyResponse(t *testing.T) {
	cli := newStubClient(t, `{
		"model":"gemma4-26b-a4b-gptq",
		"choices":[{"message":{"role":"assistant","content":"   \n  "}}],
		"usage":{"prompt_tokens":40,"completion_tokens":0,"total_tokens":40}
	}`, 200)
	editor := &FlexInferCouncilEditor{Client: cli, Model: "gemma4-26b-a4b-gptq"}

	out, err := editor.Edit(context.Background(), &council.Brief{Markdown: "Brief"}, nil)
	if err != nil {
		t.Fatalf("Edit: %v", err)
	}
	if !out.Empty {
		t.Fatalf("Empty = false, want true for whitespace-only response")
	}
	if !strings.Contains(out.Sidecar.Notes, "no content") {
		t.Fatalf("Sidecar.Notes = %q, want explanation of empty response", out.Sidecar.Notes)
	}
}

func TestFlexInferCouncilEditorNonEmptyResponseNotMarkedEmpty(t *testing.T) {
	cli := newStubClient(t, `{
		"model":"gemma4-26b-a4b-gptq",
		"choices":[{"message":{"role":"assistant","content":"## Research\nFindings."}}],
		"usage":{"prompt_tokens":40,"completion_tokens":10,"total_tokens":50}
	}`, 200)
	editor := &FlexInferCouncilEditor{Client: cli, Model: "gemma4-26b-a4b-gptq"}

	out, err := editor.Edit(context.Background(), &council.Brief{Markdown: "Brief"}, nil)
	if err != nil {
		t.Fatalf("Edit: %v", err)
	}
	if out.Empty {
		t.Fatalf("Empty = true, want false for non-empty response")
	}
}

func TestFlexInferEvalJudgeParsesContradictionVerdict(t *testing.T) {
	cli := newStubClient(t, `{
		"model":"qwen3-8b",
		"choices":[{"message":{"role":"assistant","content":"verdict: {\"score\":0.91,\"findings\":[\"consistent\"]}"}}],
		"usage":{"prompt_tokens":80,"completion_tokens":20,"total_tokens":100}
	}`, 200)
	judge := &FlexInferEvalJudge{Client: cli}

	score, findings, err := judge.JudgeContradiction(context.Background(), eval.Input{
		Sidecar:      &council.Sidecar{Models: []string{"qwen3-8b"}},
		EditorOutput: &council.EditorOutput{Documents: []council.ArtifactDoc{{Kind: council.KindImplementation, Body: "Plan"}}},
	})
	if err != nil {
		t.Fatalf("JudgeContradiction: %v", err)
	}
	if score != 0.91 {
		t.Fatalf("score = %v, want 0.91", score)
	}
	if len(findings) != 1 || findings[0] != "consistent" {
		t.Fatalf("findings = %#v", findings)
	}
}
